### ISSUE TITLE
Recipe rails app 

### ISSUE THREAD

**Issue by redwing555** [redwing555/recipe-app#11]
This is the link for the kanban board:  [The KANBAN Baord](https://github.com/redwing555/recipe-app/projects/1)

We are a team of 2 people : 

- Team member 1: @mmsesay 
- Team member 2: @redwing555

**Comment by elyor-doniyorov** [comment]
Hi @redwing555 and @mmsesay, 

Your Kanban board milestone is complete!  There is nothing else to say other than... you can start working on the tasks now :shipit: 
Congratulations! 🎉 
## STATUS APPROVED ✅ 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
